vim.cmd("colorscheme catppuccin")

require("afnan.options")
require("afnan.pack")
require("afnan.completion")
require("afnan.snacks")
require("afnan.autocommands")
require("afnan.keymaps")
require("afnan.lsp")
require("afnan.discord")
require("afnan.winbar")
require("afnan.indentline")
require("afnan.treesitter")
require("afnan.harpoon")
require("afnan.git")
require("afnan.statusline")

