require("afnan.options")
require("afnan.pack")
require("afnan.statusline")
require("afnan.completion")
require("afnan.snacks")
require("afnan.autocommands")
require("afnan.keymaps")
require("afnan.lsp")

vim.cmd("colorscheme catppuccin")
