vim.cmd("colorscheme catppuccin")
vim.loader.enable()

require("afnan.options")
require("afnan.pack")
require("afnan.snacks")
require("afnan.autocommands")
require("afnan.keymaps")
require("afnan.lsp")
require("afnan.discord")
require("afnan.winbar")
require("afnan.indentline")
require("afnan.treesitter")
require("afnan.harpoon")
require("afnan.git")
require("afnan.statusline")
require("afnan.ai")
require("afnan.noneckpain")
require("afnan.comfy-line-numbers")

vim.opt.rtp:append("/home/afnan/dev/present.nvim")
vim.opt.rtp:append("/home/afnan/dev/docker-containers.nvim/")
