return {
	"utilyre/barbecue.nvim",
	name = "barbecue",
	version = "*",
	dependencies = {
		"SmiteshP/nvim-navic",
		"nvim-tree/nvim-web-devicons",
	},
	opts = {},
	config = function()
		vim.opt.updatetime = 200

		vim.api.nvim_create_autocmd({
			"WinResized",
			"BufWinEnter",
			"CursorHold",
			"InsertLeave",
			"BufModifiedSet",
		}, {
			group = vim.api.nvim_create_augroup("barbecue.updater", {}),
			callback = function()
				require("barbecue.ui").update()
			end,
		})
		require("barbecue").setup({
			create_autocmd = false,
			symbols = {
				modified = "●",
				ellipsis = "…",
				separator = ">",
			},
			kinds = {
				Text = "  ",
				Method = "  ",
				Namespace = "  ",
				Function = "  ",
				Constructor = "  ",
				Package = "  ",
				Field = "  ",
				Variable = "[]",
				Class = " פּ ",
				Interface = " 蘒 ",
				Module = "  ",
				Property = "  ",
				Unit = "  ",
				Value = "  ",
				Enum = "  ",
				Keyword = "  ",
				Snippet = "  ",
				Color = "  ",
				File = "  ",
				Reference = "  ",
				Folder = "  ",
				EnumMember = "  ",
				Constant = "  ",
				Struct = "  ",
				String = " 𝓐 ",
				Number = " # ",
				Boolean = " ⊨ ",
				Event = "  ",
				Operator = "  ",
				TypeParameter = "  ",
				Array = "  ",
				Key = "  ",
				Null = "",
			},
		})
		local symbols = {
			File = { icon = "", hl = "@text.uri" },
			Module = { icon = "", hl = "@namespace" },
			Namespace = { icon = "", hl = "@namespace" },
			Package = { icon = "", hl = "@namespace" },
			Class = { icon = "𝓒", hl = "@type" },
			Method = { icon = "ƒ", hl = "@method" },
			Property = { icon = "", hl = "@method" },
			Field = { icon = "", hl = "@field" },
			Constructor = { icon = "", hl = "@constructor" },
			Enum = { icon = "ℰ", hl = "@type" },
			Interface = { icon = "ﰮ", hl = "@type" },
			Function = { icon = "", hl = "@function" },
			Variable = { icon = "", hl = "@constant" },
			Constant = { icon = "", hl = "@constant" },
			String = { icon = "𝓐", hl = "@string" },
			Number = { icon = "#", hl = "@number" },
			Boolean = { icon = "⊨", hl = "@boolean" },
			Array = { icon = "", hl = "@constant" },
			Object = { icon = "⦿", hl = "@type" },
			Key = { icon = "🔐", hl = "@type" },
			Null = { icon = "NULL", hl = "@type" },
			EnumMember = { icon = "", hl = "@field" },
			Struct = { icon = "𝓢", hl = "@type" },
			Event = { icon = "🗲", hl = "@type" },
			Operator = { icon = "+", hl = "@operator" },
			TypeParameter = { icon = "𝙏", hl = "@parameter" },
			Component = { icon = "", hl = "@function" },
			Fragment = { icon = "", hl = "@constant" },
		}
	end,
}
