return {
	-- Plugin for running shell commands in terminal buffers or tmux panes.
	--[[ {
		"samharju/yeet.nvim",
		requires = { "stevearc/dressing.nvim" },
		cmd = "Yeet",
		config = function()
			require("yeet").setup({
				yeet_and_run = true,
				interrupt_before_yeet = false,
				clear_before_yeet = true,
				notify_on_success = false,
				warn_tmux_not_running = true,
				cache_window_opts = function()
					return {
						relative = "editor",
						row = (vim.o.lines - 15) * 0.5,
						col = (vim.o.columns - math.ceil(0.6 * vim.o.columns)) * 0.5,
						width = math.ceil(0.6 * vim.o.columns),
						height = 15,
						border = "none",
						title = "Yeet",
					}
				end,
			})
		end,
	}, ]]
	{
		"nvchad/showkeys",
		cmd = "ShowkeysToggle",
		opts = {
			timeout = 1,
			maxkeys = 4,
			winopts = { border = "none" },
			show_count = true,
			keyformat = {
				["<BS>"] = "<- ",
				["<CR>"] = "CR",
				["<Space>"] = "_",
				["<Up>"] = "Up",
				["<Down>"] = "Down",
				["<Left>"] = "Left",
				["<Right>"] = "Right",
				["<PageUp>"] = "Page Up",
				["<PageDown>"] = "Page Down",
				["<M>"] = "Alt",
				["<C>"] = "Ctrl",
			},
		},
	},
	--[[ {
      "m4xshen/hardtime.nvim",
      dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
      opts = {
         restricted_keys = {
            ["h"] = {},
            ["l"] = {},
            ["j"] = {},
            ["k"] = {},
            ['<Up>'] = { 'n', 'x', 'i', 'v' },
            ['<Down>'] = { 'n', 'x', 'i', 'v' },
            ['<Left>'] = { 'n', 'x', 'i', 'v' },
            ['<Right>'] = { 'n', 'x', 'i', 'v' },
         },
         disabled_keys = {
            ["<Up>"] = {},
            ["<Down>"] = {},
            ["<Left>"] = {},
            ["<Right>"] = {},
         },
      },
   }, ]]
	{
		"christoomey/vim-tmux-navigator",
		cmd = {
			"TmuxNavigateLeft",
			"TmuxNavigateDown",
			"TmuxNavigateUp",
			"TmuxNavigateRight",
			"TmuxNavigatePrevious",
			"TmuxNavigatorProcessList",
		},
		keys = {
			{ "<c-h>", "<cmd><C-U>TmuxNavigateLeft<cr>" },
			{ "<c-j>", "<cmd><C-U>TmuxNavigateDown<cr>" },
			{ "<c-k>", "<cmd><C-U>TmuxNavigateUp<cr>" },
			{ "<c-l>", "<cmd><C-U>TmuxNavigateRight<cr>" },
			{ "<c-\\>", "<cmd><C-U>TmuxNavigatePrevious<cr>" },
		},
	},
	{
		"ThePrimeagen/refactoring.nvim",
		dependencies = {
			"nvim-lua/plenary.nvim",
			"nvim-treesitter/nvim-treesitter",
		},
		lazy = true,
		opts = {
			prompt_func_return_type = {
				go = false,
				java = false,
				cpp = false,
				c = false,
				h = false,
				hpp = false,
				cxx = false,
				javascript = true,
			},
			prompt_func_param_type = {
				go = false,
				java = false,
				javascript = true,
				cpp = false,
				c = false,
				h = false,
				hpp = false,
				cxx = false,
			},
			printf_statements = {},
			print_var_statements = {},
			show_success_message = true,
		},
	},
	{ "wakatime/vim-wakatime", lazy = false },
	{ "shortcuts/no-neck-pain.nvim", version = "*" },
	-- { "glacambre/firenvim", build = ":call firenvim#install(0)" },
	{
		"mluders/comfy-line-numbers.nvim",
		config = function()
			require("comfy-line-numbers").setup({
				labels = {
					"1",
					"2",
					"3",
					"4",
					"5",
					"11",
					"12",
					"13",
					"14",
					"15",
					"21",
					"22",
					"23",
					"24",
					"25",
					"31",
					"32",
					"33",
					"34",
					"35",
					"41",
					"42",
					"43",
					"44",
					"45",
					"51",
					"52",
					"53",
					"54",
					"55",
					"111",
					"112",
					"113",
					"114",
					"115",
					"121",
					"122",
					"123",
					"124",
					"125",
					"131",
					"132",
					"133",
					"134",
					"135",
					"141",
					"142",
					"143",
					"144",
					"145",
					"151",
					"152",
					"153",
					"154",
					"155",
					"211",
					"212",
					"213",
					"214",
					"215",
					"221",
					"222",
					"223",
					"224",
					"225",
					"231",
					"232",
					"233",
					"234",
					"235",
					"241",
					"242",
					"243",
					"244",
					"245",
					"251",
					"252",
					"253",
					"254",
					"255",
				},
				up_key = "k",
				down_key = "j",

				hidden_file_types = { "undotree" },
				hidden_buffer_types = { "terminal", "nofile" },
			})
		end,
	},
}
